### ISSUE TITLE
Feature Request: Automate HttpRequest Header & Authentication

### ISSUE THREAD

**Issue by EiTaNBaRiBoA** [Swarkin/Godot-AwaitableHTTPRequest#9]
**Current difficulties**

- Configuring headers (content-type, etc.) for each HttpRequest manually is tedious & error-prone.
- Handling authentication, especially different schemes like Bearer tokens, adds complexity.

**Proposed Improvements**

- Auto-detect Content-Type: Automatically infer the content-type from the request data, minimizing manual setup.
- Simplified Authentication: Introduce an auth parameter to handle various authentication types (e.g., 'Bearer', 'Basic') along with the credentials. The system would then generate the correct authentication headers.

**Benefits**

- Developer-friendly: Make HttpRequests easier to set up, reducing boilerplate & potential mistakes
- Efficiency Boost: Save development time through automated header & authentication configuration.
- Cleaner Code: Abstract header & authentication details for improved readability.

**Example Usage**
```GDScript
var request = HttpRequest.new()
request.url = "https://api.example.com/data"
request.method = HTTPClient.METHOD_POST
request.auth = {"type": "Bearer", "token": "my_bearer_token"}
# Content-type is auto-detected based on request.body 
```

- Customization: Allow overrides for auto-detected headers or authentication if needed.
- Error Handling: Provide clear error messages for failed auto-detection or invalid authentication.

**Comment by Swarkin** [comment]
Hi!

I want to keep the API simple and close to the regular HTTPRequest Node, which allows the dev total control over its behaviour.
In order to implement most features you mentioned (for example; auto-detection of the content type), the API would have to be expanded and/or changed drastically which I don't think fits very well into this addon. On top of that, ambiguous behaviour would be introduced which is something that may lead to confusion and again contradict my initial goal of providing a simple, almost drop-in awaitable solution for HTTP requests.

You are welcome to create a fork and implement your changes, as well as upload it to the asset lib as a separate addon for users in need of more advanced HTTP Nodes.

I appreciate your interest in the addon!
